import "@/styles/globals.css";
import Image from "next/image";
import Head from "next/head";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import profilePic from "../../public/images/p.png";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: "300",
  display: "swap",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center w-full bg-tertiary">
        <Layout className="min-h-screen">
          {/* sidebar */}
          <div className="sidebar hidden md:flex md:max-w-[685px]:hidden">
            <a href="#" className="px-2">
              UI Developer
            </a>
            <span></span>
            <a href="#" className="px-2">
              2025
            </a>
          </div>
          <div className="flex flex-col md:flex-row items-center jusify-between w-full">
            {/* Left col */}
            <div className="w-full md:w-1/2 flex flex-col items-center md:items-start text-center md:text-left">
              <div className="w-full flex mb-8 justify-center md:justify-center">
                <div className="flex flex-col items-center md:items-start m-3">
                  <div className={`${roboto.className} text-5xl`}>
                    <sup className="text-2xl">+</sup>100
                  </div>
                  <div className="text-sm text-gray-700">
                    Projects Completed
                  </div>
                </div>
                <div className="flex flex-col items-center md:items-start m-3">
                  <div className={`${roboto.className} text-5xl`}>
                    <sup className="text-2xl">+</sup>9
                  </div>
                  <div className="text-sm text-gray-700">Startups Raised</div>
                </div>
              </div>
              <AnimatedText text="Hello" className="text-9xl text-center" />
              <p className="w-full text-center">
                - It's is MSravani design world
              </p>
              <div className="mt-10 w-full text-center">
                <a
                  href="#"
                  className="text-gray-500 text-sm hover:text-gray-700"
                >
                  Scroll Down ↓
                </a>
              </div>
            </div>
            {/* Right col */}
            <div className="w-full md:w-1/2 flex justify-center md:justify-end mt-8 md:mt-0">
            <div className="w-full h-[400px] md:h-full relative">
              <Image
                src={profilePic}
                alt="sravani"
                className="object-cover w-full h-full"
              />
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
